import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {io,Socket} from 'socket.io-client';
import './styles.css';

type User={id:string;username:string;displayName:string;avatarUrl?:string|null};
type Server={id:string;name:string;description?:string|null;channels:{id:string;name:string;type:string}[]};
type Message={id:string;content:string;createdAt:string;author:User};
const API=import.meta.env.VITE_API_URL??'http://localhost:3000';

async function api<T>(path:string,options:RequestInit={}){const token=localStorage.getItem('loelsti_token');const res=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});const data=await res.json();if(!res.ok)throw new Error(data.message??'Anfrage fehlgeschlagen.');return data as T;}

function App(){
 const [user,setUser]=useState<User|null>(null);const [servers,setServers]=useState<Server[]>([]);const [activeServer,setActiveServer]=useState<Server|null>(null);const [channel,setChannel]=useState<string|null>(null);const [messages,setMessages]=useState<Message[]>([]);const [text,setText]=useState('');const [authMode,setAuthMode]=useState<'login'|'register'>('login');const [error,setError]=useState('');const [socket,setSocket]=useState<Socket|null>(null);
 const activeChannel=useMemo(()=>activeServer?.channels.find(c=>c.id===channel),[activeServer,channel]);
 useEffect(()=>{const boot=async()=>{if(!localStorage.getItem('loelsti_token'))return;try{const me=await api<{user:User}>('/api/v1/me');setUser(me.user);const s=await api<{servers:Server[]}>('/api/v1/servers');setServers(s.servers);if(s.servers[0]){setActiveServer(s.servers[0]);setChannel(s.servers[0].channels.find(c=>c.type==='TEXT')?.id??null)}}catch{localStorage.removeItem('loelsti_token')}};boot()},[]);
 useEffect(()=>{if(!user)return;const s=io(API,{auth:{token:localStorage.getItem('loelsti_token')}});s.on('connect',()=>servers.forEach(x=>s.emit('subscribeServer',x.id)));s.on('MESSAGE_CREATE',(m:Message)=>setMessages(prev=>prev.some(x=>x.id===m.id)?prev:[...prev,m]));setSocket(s);return()=>{s.disconnect()}},[user,servers.length]);
 useEffect(()=>{if(!channel)return;api<{messages:Message[]}>(`/api/v1/channels/${channel}/messages`).then(x=>setMessages(x.messages)).catch(e=>setError(e.message))},[channel]);
 async function submitAuth(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');const fd=new FormData(e.currentTarget);try{const data=authMode==='login'?await api<{token:string;user:User}>('/api/v1/auth/login',{method:'POST',body:JSON.stringify({login:fd.get('login'),password:fd.get('password')})}):await api<{token:string;user:User}>('/api/v1/auth/register',{method:'POST',body:JSON.stringify({username:fd.get('username'),displayName:fd.get('displayName'),email:fd.get('email'),password:fd.get('password')})});localStorage.setItem('loelsti_token',data.token);setUser(data.user)}catch(e){setError(e instanceof Error?e.message:'Fehler')}}
 async function sendMessage(){if(!channel||!text.trim())return;try{const d=await api<{message:Message}>(`/api/v1/channels/${channel}/messages`,{method:'POST',body:JSON.stringify({content:text.trim()})});setMessages(p=>p.some(m=>m.id===d.message.id)?p:[...p,d.message]);setText('')}catch(e){setError(e instanceof Error?e.message:'Fehler')}}
 async function createServer(){const name=prompt('Wie soll der Server heißen?');if(!name)return;try{const d=await api<{server:Server}>('/api/v1/servers',{method:'POST',body:JSON.stringify({name})});setServers(p=>[...p,d.server]);setActiveServer(d.server);setChannel(d.server.channels.find(c=>c.type==='TEXT')?.id??null)}catch(e){setError(e instanceof Error?e.message:'Fehler')}}
 if(!user)return <main className="auth"><div className="brand"><div className="logo">L</div><div><h1>LOELSTI</h1><p>Deine Community. Echtzeit. Gemeinsam.</p></div></div><form onSubmit={submitAuth} className="card"><h2>{authMode==='login'?'Willkommen zurück':'Konto erstellen'}</h2>{authMode==='register'&&<><input name="username" placeholder="Username" required/><input name="displayName" placeholder="Anzeigename" required/><input name="email" type="email" placeholder="E-Mail" required/></>}<input name="login" placeholder="Username oder E-Mail" required style={{display:authMode==='register'?'none':undefined}}/><input name="password" type="password" placeholder="Passwort" minLength={8} required/><button>{authMode==='login'?'Einloggen':'Registrieren'}</button>{error&&<div className="error">{error}</div>}<button type="button" className="ghost" onClick={()=>setAuthMode(authMode==='login'?'register':'login')}>{authMode==='login'?'Neues Konto erstellen':'Ich habe bereits ein Konto'}</button></form></main>;
 return <div className="app"><aside className="servers"><div className="logo small">L</div>{servers.map(s=><button key={s.id} className={activeServer?.id===s.id?'server active':'server'} onClick={()=>{setActiveServer(s);setChannel(s.channels.find(c=>c.type==='TEXT')?.id??null)}}>{s.name.slice(0,2).toUpperCase()}</button>)}<button className="server add" onClick={createServer}>+</button></aside><aside className="channels"><div className="server-head"><strong>{activeServer?.name??'LOELSTI'}</strong></div>{activeServer?.channels.filter(c=>c.type==='TEXT').map(c=><button key={c.id} className={channel===c.id?'channel active':'channel'} onClick={()=>setChannel(c.id)}># {c.name}</button>)}<div className="userbar"><div><b>{user.displayName}</b><span>@{user.username}</span></div><button onClick={()=>{localStorage.removeItem('loelsti_token');location.reload()}}>↪</button></div></aside><main className="chat"><header><div><h2>#{activeChannel?.name??'general'}</h2><span>{activeServer?.description??'Willkommen bei LOELSTI'}</span></div></header><section className="messages">{messages.map(m=><article className="message" key={m.id}><div className="avatar">{m.author.displayName.slice(0,1).toUpperCase()}</div><div><div className="meta"><b>{m.author.displayName}</b><time>{new Date(m.createdAt).toLocaleString('de-DE')}</time></div><p>{m.content}</p></div></article>)}</section><div className="composer"><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}}} placeholder={activeChannel?`Nachricht in #${activeChannel.name}`:'Wähle einen Kanal'} disabled={!channel}/><button onClick={sendMessage} disabled={!text.trim()||!channel}>Senden</button></div>{error&&<div className="toast error">{error}</div>}</main></div>
}
createRoot(document.getElementById('root')!).render(<App/>);
